### ISSUE TITLE
esp32

### ISSUE THREAD

**Issue by anrada73** [GyverLibs/GyverShift#1]
Привет, эта библиотека не  работает с esp32, всё компримируется, но ничего не происходит. То же самое подключение прекрасно работает с вашей библиотекой #include <GyverHC595.h>  Пины на esp32 используются 18, 2, 4.
Gyvershift нужен был изза возможности использовать toggle функцию, а пришлось ее добавить  в GyverHC595.

P.S. Ответ на твой ответ: если библиотека кривая, то это указывать надо.

**Comment by GyverLibs** [comment]
привет, библиотека отлично работает на esp32. Возможно у тебя кривое подключение и нужно объявить `GSHIFTT_DELAY` для снижения скорости интерфейса. В стоке на esp32 получается 6 МГц
